---
- hosts: web-tier
  remote_user: root
  become: yes
  gather_facts: False
  tasks:
  - name: Upgrade pip
    pip: name=pip state=latest
    tags:
      - packages
  - name: Copy wordpress directory to server
    copy:
      src: wordpress.tar.gz
      dest: /root/wordpress.tar.gz
      owner: www-data
      group: www-data
      mode: 0755
  - name: Unpack Wordpress to /var/www/html
    shell: |
      sudo mkdir /var/www/wordpress
      sudo tar -xzvf /root/wordpress.tar.gz -C /var/www/wordpress
      sudo chown -R www-data:www-data /var/www/wordpress
      sudo chmod -R 755 /var/www/wordpress
  - name: Copy wordpress directory to server
    copy:
      src: default.conf
      dest: /etc/nginx/conf.d
      owner: root
      group: root
      mode: 0755
  - name: restart nginx
    shell: |
       sudo nginx -s reload